### ISSUE TITLE
Problem accessing /adaptor-rm/services/requirements/query. Reason:       Server Error

### ISSUE THREAD

**Issue by BIT-masterpy** [OSLC/lyo-adaptor-sample-modelling#23]
`Caused by:
javax.servlet.ServletException: java.lang.NoClassDefFoundError: org/apache/jena/ext/com/google/common/base/Strings
	at org.apache.wink.server.internal.RequestProcessor.handleRequest(RequestProcessor.java:195)
	at org.apache.wink.server.internal.servlet.RestServlet.service(RestServlet.java:119)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/apache/jena/ext/com/google/common/base/Strings
	at org.eclipse.lyo.oslc4j.core.OSLC4JUtils.parseBooleanPropertyOrDefault(OSLC4JUtils.java:546)
	at org.eclipse.lyo.oslc4j.core.OSLC4JUtils.alwaysAbbrevXML(OSLC4JUtils.java:95)
	at org.eclipse.lyo.oslc4j.provider.jena.AbstractOslcRdfXmlProvider.getSerializationLanguage(AbstractOslcRdfXmlProvider.java:278)
	at org.eclipse.lyo.oslc4j.provider.jena.AbstractOslcRdfXmlProvider.writeTo(AbstractOslcRdfXmlProvider.java:234)
	at org.eclipse.lyo.oslc4j.provider.jena.OslcRdfXmlArrayProvider.writeTo(OslcRdfXmlArrayProvider.java:92)
	at org.eclipse.lyo.oslc4j.provider.jena.OslcRdfXmlArrayProvider.writeTo(OslcRdfXmlArrayProvider.java:39)
	at org.apache.wink.server.internal.handlers.FlushResultHandler.handleResponse(FlushResultHandler.java:199)
	at org.apache.wink.server.handlers.AbstractHandler.handleResponse(AbstractHandler.java:38)
	at org.apache.wink.server.handlers.ResponseHandlersChain.handle(ResponseHandlersChain.java:26)
	at org.apache.wink.server.handlers.ResponseHandlersChain.handle(ResponseHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
	at org.apache.wink.server.handlers.AbstractHandler.handleResponse(AbstractHandler.java:39)
	at org.apache.wink.server.handlers.ResponseHandlersChain.handle(ResponseHandlersChain.java:26)
	at org.apache.wink.server.handlers.ResponseHandlersChain.handle(ResponseHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
	at org.apache.wink.server.handlers.AbstractHandler.handleResponse(AbstractHandler.java:39)
	at org.apache.wink.server.handlers.ResponseHandlersChain.handle(ResponseHandlersChain.java:26)
	at org.apache.wink.server.handlers.ResponseHandlersChain.handle(ResponseHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
	at org.apache.wink.server.internal.log.Responses.handleResponse(Responses.java:90)
	at org.apache.wink.server.handlers.ResponseHandlersChain.handle(ResponseHandlersChain.java:26)
	at org.apache.wink.server.handlers.ResponseHandlersChain.handle(ResponseHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
	at org.apache.wink.server.handlers.AbstractHandlersChain.run(AbstractHandlersChain.java:48)
	at org.apache.wink.server.internal.RequestProcessor.handleRequestWithoutFaultBarrier(RequestProcessor.java:212)
	at org.apache.wink.server.internal.RequestProcessor.handleRequest(RequestProcessor.java:154)
	... 27 more

`

**Comment by berezovskyi** [comment]
How did you run the code?

**Comment by jadelkhoury** [comment]
I just tested with running the adaptor-rm and I cannot reproduce the problem. The request 
http://localhost:8081/adaptor-rm/services/requirements/query returns expected results, both as html and as application/rdf+xml.

Can you please clarify when you receive this problem?

**Comment by berezovskyi** [comment]
@BIT-masterpy you still did not write how exactly did you run this code.
