### ISSUE TITLE
 ERROR com.sample.testing.TestingToolManager - Failed to query resources

### ISSUE THREAD

**Issue by BIT-masterpy** [OSLC/lyo-adaptor-sample-modelling#26]
![2019-04-03_180321](https://user-images.githubusercontent.com/30205233/55471004-63dd0880-563b-11e9-97c8-86f0b6a97e8b.png)

![2019-04-03_180354](https://user-images.githubusercontent.com/30205233/55471026-6e979d80-563b-11e9-84ca-880d5406b294.png)

`[qtp1996248711-24] INFO org.apache.wink.common.internal.application.ApplicationFileLoader - The runtime is loading the JAX-
RS application from jar:file:/C:/Users/1/Desktop/oslc/lyo-adaptor-sample-modelling/adaptor-testing-webapp/target/adaptor-te
sting-webapp-0.0.1-SNAPSHOT/WEB-INF/lib/wink-json4j-provider-1.2.1-incubating.jar!/META-INF/wink-application
[qtp1996248711-24] ERROR com.sample.testing.TestingToolManager - Failed to query resources
java.lang.RuntimeException: A javax.ws.rs.ext.MessageBodyReader implementation was not found for class org.eclipse.lyo.oslc
4j.core.model.ServiceProviderCatalog type and text/html;charset=utf-8 media type.  Verify that all entity providers are cor
rectly registered.  Add a custom javax.ws.rs.ext.MessageBodyReader provider to handle the type and media type if a JAX-RS e
ntity provider does not currently exist.
        at org.apache.wink.client.internal.handlers.ClientResponseImpl.readEntity(ClientResponseImpl.java:122)
        at org.apache.wink.client.internal.handlers.ClientResponseImpl.getEntity(ClientResponseImpl.java:65)
        at org.apache.wink.client.internal.handlers.ClientResponseImpl.getEntity(ClientResponseImpl.java:52)

`

`[qtp1996248711-24] INFO org.apache.wink.server.internal.RequestProcessor - The following error occurred during the invocati
on of the handlers chain: NoClassDefFoundError with message 'org/apache/jena/ext/com/google/common/base/Strings' while proc
essing GET request sent to http://localhost:8082/adaptor-testing/services/serviceProviders/1/testScripts/872
[qtp1996248711-24] ERROR org.apache.wink.server.internal.RequestProcessor - An unhandled exception occurred which will be p
ropagated to the container.
java.lang.NoClassDefFoundError: org/apache/jena/ext/com/google/common/base/Strings
        at org.eclipse.lyo.oslc4j.core.OSLC4JUtils.parseBooleanPropertyOrDefault(OSLC4JUtils.java:546)
        at org.eclipse.lyo.oslc4j.core.OSLC4JUtils.alwaysAbbrevXML(OSLC4JUtils.java:95)
        at org.eclipse.lyo.oslc4j.provider.jena.AbstractOslcRdfXmlProvider.getSerializationLanguage(AbstractOslcRdfXmlProvi
der.java:278)
`

`[WARNING]
javax.servlet.ServletException: java.lang.NoClassDefFoundError: org/apache/jena/ext/com/google/common/base/Strings
    at org.apache.wink.server.internal.RequestProcessor.handleRequest (RequestProcessor.java:195)
    at org.apache.wink.server.internal.servlet.RestServlet.service (RestServlet.java:119)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle (ServletHolder.java:837)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle (ServletHandler.java:583)
`

`[WARNING]
javax.servlet.ServletException: java.lang.NoClassDefFoundError: org/apache/jena/ext/com/google/common/base/Strings
    at org.apache.wink.server.internal.RequestProcessor.handleRequest (RequestProcessor.java:195)
    at org.apache.wink.server.internal.servlet.RestServlet.service (RestServlet.java:119)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle (ServletHolder.java:837)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle (ServletHandler.java:583)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle (SecurityHandler.java:548)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle (SessionHandler.java:226)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle (ContextHandler.java:1174)
    at org.eclipse.jetty.servlet.ServletHandler.doScope (ServletHandler.java:511)
    at org.eclipse.jetty.server.session.SessionHandler.doScope (SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope (ContextHandler.java:1106)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle (ContextHandlerCollection.java:213)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle (HandlerCollection.java:119)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:134)
    at org.eclipse.jetty.server.Server.handle (Server.java:524)
    at org.eclipse.jetty.server.HttpChannel.handle (HttpChannel.java:319)
    at org.eclipse.jetty.server.HttpConnection.onFillable (HttpConnection.java:253)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:273)
    at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run (SelectChannelEndPoint.java:93)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume (ExecuteProduceConsume.java:303)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume (ExecuteProduceConsume.java:148)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run (ExecuteProduceConsume.java:136)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:671)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run (QueuedThreadPool.java:589)
    at java.lang.Thread.run (Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/apache/jena/ext/com/google/common/base/Strings
    at org.eclipse.lyo.oslc4j.core.OSLC4JUtils.parseBooleanPropertyOrDefault (OSLC4JUtils.java:546)
    at org.eclipse.lyo.oslc4j.core.OSLC4JUtils.alwaysAbbrevXML (OSLC4JUtils.java:95)
    at org.eclipse.lyo.oslc4j.provider.jena.AbstractOslcRdfXmlProvider.getSerializationLanguage (AbstractOslcRdfXmlProvider
.java:278)
    at org.eclipse.lyo.oslc4j.provider.jena.AbstractOslcRdfXmlProvider.writeTo (AbstractOslcRdfXmlProvider.java:234)
    at org.eclipse.lyo.oslc4j.provider.jena.OslcCompactRdfProvider.writeTo (OslcCompactRdfProvider.java:86)
    at org.eclipse.lyo.oslc4j.provider.jena.OslcCompactRdfProvider.writeTo (OslcCompactRdfProvider.java:39)
    at org.apache.wink.server.internal.handlers.FlushResultHandler.handleResponse (FlushResultHandler.java:199)
    at org.apache.wink.server.handlers.AbstractHandler.handleResponse (AbstractHandler.java:38)
`

**Comment by BIT-masterpy** [comment]
**Unable to create new resource**

![2019-04-03_210540](https://user-images.githubusercontent.com/30205233/55481183-626c0a00-5654-11e9-924c-d48a73ba1e3d.png)

**Comment by berezovskyi** [comment]
Creation requests don't work with a browser. Please use a REST client like Postman or Insomnia and make sure to use RDF MIME types.

**Comment by BIT-masterpy** [comment]
@jadelkhoury    How to solve this problem?
